### PR TITLE
Fix install from VSIX for TAR and ZIP formats

### LINKED ISSUE #92: Detect archive type of extension to decompress
We've filled the client zip implementation with tar so we can eventually load extensions on the client. Installing from a VSIX no longer works because the standard format is a zip.

We should detect the archive type then use the appropriate fill.

### PR DESCRIPTION
**Pull request by foresthoffman**
### Describe in detail the problem you had and how this PR fixes it
Fixes installing extensions from VSIX files formatted as either TAR or ZIP.

### Is there an open issue you can link to?
Fixes #92

### CODE REVIEW

File: packages/vscode/src/fill/zip.ts [hunk 1]
```diff
@@ -58,81 +58,38 @@ export function zip(tarPath: string, files: IFile[]): Promise<string> {
...
-	const sourcePathRegex = new RegExp(options.sourcePath ? `^${options.sourcePath}` : '');
-
+export async function extract(archivePath: string, extractPath: string, options: IExtractOptions = {}, token: CancellationToken): Promise<void> {
 	return new Promise<void>(async (c, e) => {
-		const buffer = await promisify(fs.readFile)(tarPath);
-		const extractor = tarStream.extract();
-		extractor.once('error', e);
-		extractor.on('entry', (header, stream, next) => {
-			const rawName = header.name;
+		extractZip(archivePath, extractPath, options, token).then(c).catch((ex) => {
```
Comment (kylecarbs) [inline packages/vscode/src/fill/zip.ts]: Should we try extracting a tar first? We expect _most_ extensions to be in the tar format.

Comment (foresthoffman) [reply packages/vscode/src/fill/zip.ts]: That makes sense, extraction only occurs for installing from the marketplace.
